config/routes.rb
Rails.application.routes.draw do
  resources :plans
	resources :tasks
	resources :completions
	root to: "plans#index"
	get 'users/new' => 'users#new', as: :new_user
	post 'users' => 'users#create'
  get '/login' => 'sessions#new'
	post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
	delete '/completions' => 'completions#destroy'
end

app/models/plan.rb
class Plan < ApplicationRecord
  include PlanConcern
  belongs_to :user
  has_many :completions, as: :completable
  before_destroy { self.completions.destroy_all }
  has_many :tasks, dependent: :delete_all
  validates_presence_of :title

  def completed_for_day?(day)
    self.completions.where(completed_on: day).exists?
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :set_plan, only: %i[ show edit update destroy ]
  helper_method :plan_date

  def plan_date
    date = params[:date].presence || Date.today.to_s
    return Date.parse date
    rescue Date::Error
      Date.today
  end

  # GET /plans or /plans.json
  def index
    if !current_user
      redirect_to :login
    else
      user_id = User.find(current_user.id).id
      @plans = Plan.where(user: user_id)
    end

    render_to_string @plans
  end

  # GET /plans/1 or /plans/1.json
  def show
    @task = Task.new(user_id: current_user)
  end

  # GET /plans/new
  def new
    redirect_to :root if !current_user
    @plan = Plan.new
  end

  # GET /plans/1/edit
  def edit
  end

  # POST /plans or /plans.json
  def create
    @plan = Plan.new(title: plan_params[:title], user_id: current_user.id)

    respond_to do |format|
      if @plan.save
        format.html { redirect_to plan_url(@plan), notice: "Plan was successfully created." }
        format.json { render :show, status: :created, location: @plan }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plans/1 or /plans/1.json
  def update
    respond_to do |format|
      if @plan.update(plan_params)
        format.html { redirect_to plan_url(@plan), notice: "Plan was successfully updated." }
        format.json { render :show, status: :ok, location: @plan }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plans/1 or /plans/1.json
  def destroy
    @plan.destroy

    respond_to do |format|
      format.html { redirect_to plans_url, notice: "Plan was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plan
      @plan = Plan.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def plan_params
      params.require(:plan).permit(:user_id, :title, :date)
    end
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/plans/_form.html.erb
<%= form_with(model: plan) do |form| %>
  <% if plan.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(plan.errors.count, "error") %> prohibited this plan from being saved:</h2>

      <ul>
        <% plan.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/plans/_plan.html.erb
<div id="<%= dom_id plan %>">
  <p>
    <strong>Title:</strong>
    <%= plan.title %>
  </p>

</div>

app/views/plans/_task_form.html.erb
<%= form_for @task do |form| %>
  <% if @task.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% @task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>



  <div>
    <%= form.label :description, style: "display: flex flex-row" %>
    <%= form.text_field :description %>
    <%= form.hidden_field "user_id", value: current_user.id %>
    <%= form.hidden_field "plan_id", value: @plan.id %>
    <%= form.submit data: { comfirm: 'Adding a task will end your streak.' } %>
    <em>warning, adding a new task to a plan will delete your current streak if you have one.</em>
  </div>
<% end %>

app/views/plans/_task_show.html.erb
<div>
  <h1>Current Streak: <%= @plan.streak %></h1>
  <h3>Daily Tasks:</h3>
  <div>
    <ul id="plan_tasks">
      <% @plan.tasks.each do |task| %>
      
      <% if task.completed_for_day?(plan_date)%>
        <li class="task-display">
          <%= task.description %>
          <%= form_with(url: "/completions", method: :delete, local: true) do |form|%>
            <%= form.hidden_field "completable_id", value: task.id %>
            <%= form.hidden_field "completable_type", value: "Task" %>
            <%= form.hidden_field "plan_id", value: @plan.id %>
            <%= form.hidden_field "plan_date", value: plan_date %>
            <%= form.submit "Mark Incomplete", class: "btn btn-danger" %>
          <% end %>
        </li>
      <% else %>
        <li class="task-display">
            <%= task.description %>
            <div>
              <%= form_with(
                  url: "/completions", 
                  method: :post, 
                  local: true
                  ) do |form| %>
            <%= form.hidden_field "completable_id", value: task.id %>
            <%= form.hidden_field "completable_type", value: "Task" %>
            <%= form.hidden_field "plan_id", value: @plan.id %>
            <%= form.hidden_field "plan_date", value: plan_date %>
            <%= form.submit "Mark Complete", class: "btn btn-success" %>
              <% end %>
            </div>
          </li>
        <% end %>
      <% end %>
    </ul>
  </div>
</div>

app/views/plans/edit.html.erb
<h1>Editing plan</h1>

<%= render "form", plan: @plan %>

<br>

<div>
  <%= link_to "Show this plan", @plan %> |
  <%= link_to "Back to plans", plans_path %>
</div>

app/views/plans/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Plans</h1>

<% if @plans %>
<div id="plans">
  <% @plans.each do |plan| %>
    <%= render plan %>
    streak: <%= plan.streak%>
      <p>
        <%= link_to "Show this plan", plan_path(plan, date: Date.today) %>
      </p>
    <% end %>
  </div>
<% end %>

<%= link_to "New plan", new_plan_path %>

app/views/plans/new.html.erb
<h1>New plan</h1>

<%= render "form", plan: @plan %>

<br>

<div>
  <%= link_to "Back to plans", plans_path %>
</div>

app/views/plans/show.html.erb
<p style="color: green"><%= notice %></p>

<div>
  <div>
    <%= link_to '<', plan_path(@plan, date: plan_date - 1) %>
    <%= plan_date.to_s %>
    <%= link_to '>', plan_path(@plan, date: plan_date + 1) %>
  </div>
  <% if @plan.completed_for_day?(plan_date) %>
    <h1 class="completed-plan"><%= @plan.title %></h1>
  <% else %>
    <h1><%= @plan.title %></h1>
  <% end %>
  <%= render :partial => "task_show", locals: {object: plan_date} %>
</div>

<div>
  <%= render :partial => "task_form" %>
</div>
<div>
  <%= link_to "Edit this plan", edit_plan_path(@plan) %> |
  <%= link_to "Back to plans", plans_path %>

  <%= button_to "Destroy this plan", @plan, method: :delete %>
</div>